### ISSUE TITLE
powerpc-ibm-utils vs powerpc-utils

### ISSUE THREAD

**Issue by mwbringmann** [linux-ras/ServiceReport#1]
The Package Availability Check looks for 'powerpc-ibm-utils'.

Package availability check                          FAIL

  powerpc-ibm-utils                                 FAIL
  ppc64-diag                                        PASS
  perf                                              PASS
  sos                                               PASS

Is this an alternate name for 'powerpc-utils'?  I usually see the package name 'powerpc-utils' for the installed package that contains the 'drmgr', 'lparstat', 'nvram', etc. tools.

**Comment by sourabhjains** [comment]
Hello Michael,

Thanks for reporting the issue.

The powerpc-ibm-utils package is referred with different names across multiple Linux distros and such name difference is missing in ServiceReport.

Here is my observation on powerpc-ibm-utils package names:
1) RHEL           -            powerpc-utils
2) SLES           -             powerpc-utils
3) Ubuntu        -             powerpc-ibm-utils 

We will soon fix this issue.

- Sourabh Jain

**Comment by sourabhjains** [comment]
Fixed: https://github.com/linux-ras/ServiceReport/commit/1d359dab3c43f5f4c84e74279ec92106c8a42524
