### ISSUE TITLE
servicereport HTX check output for customer use case / verbose explanation on checks that FAIL 

### ISSUE THREAD

**Issue by rvetapal** [linux-ras/ServiceReport#14]
When servicereport is executed, one of the checks it does is HTX configuration. HTX, though now open source, is a Test tool and not a required package. It is at least not expected to be used by customers in the field. Customers are very likely not even aware what HTX is. Marking it as "FAIL" without any further explanation or guidance unnecessarily alarms the customer. Even the documentation on service report doesn't state what HTX is and what to expect if the check for HTX returns FAIL.

Typical servicereport output on a customer system:
   Daemon check		PASS
   HTX configuration check   FAIL
   kdump check		PASS 
   ...			
   ...

There is scope to improve the consumability of the servicereport output by making it easy to interpret its findings.
e.g. Whenever a check done by servicereport detects something that it marks as "FAIL", there could be verbose output (it may be made default or on use of a verbose flag) to provide specific guidance on how to interpret it and what potential actions could be taken.
Specifically for HTX, consider whether it is appropriate to include it as a default check in servicereport. It may have made sense for the internal Test team consumers but need to rethink on it from external users perspective.

**Comment by sourabhjains** [comment]
Thanks @rvetapal  for reporting the issue.

We have marked the htx plugin as an option and removed it from the default run. Now interested users can explicitly enable htx plugin using -o option.

**Comment by sourabhjains** [comment]
Now the default looks something like this:

servicereport 2.2.2

Daemon availability checks                          PASS

Kdump configuration check                           PASS

Package availability check                          PASS

I hope this resolves your concern. Please let us know if you have more comments on this issue else you can close the issue.

**Comment by rvetapal** [comment]
Yes, it addresses the stated concern. Thank you.
Ensure to make any required documentation updates. It would also be good to explicitly communicate to the internal Test teams, who would be the end-users interested in exercising the HTX check regularly, about this change in default behaviour.
