### ISSUE TITLE
ServiceReport failed to install due unavailability of /usr/bin/python

### ISSUE THREAD

**Issue by sourabhjains** [linux-ras/ServiceReport#16]
make install
python setup.py install
make: python: Command not found
make: *** [Makefile:13: install] Error 127

**Comment by olafWW** [comment]
easy .. your install is most likely RHEL 8 ? .. you need to specify your python by:
[root@fscc-sr650-19 ServiceReport]# make build
python setup.py build
make: python: Command not found
make: *** [Makefile:9: build] Error 127
[root@fscc-sr650-19 ServiceReport]# alternatives --config python

There are 2 programs which provide 'python'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/libexec/no-python
   2           /usr/bin/python3

Enter to keep the current selection[+], or type selection number: 2
[root@fscc-sr650-19 ServiceReport]# make build                  
python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/servicereportpkg
copying servicereportpkg/__init__.py -> build/lib/servicereportpkg
copying servicereportpkg/check.py -> build/lib/servicereportpkg
copying servicereportpkg/file_manager.py -> build/lib/servicereportpkg
copying servicereportpkg/global_context.py -> build/lib/servicereportpkg
[...]

**Comment by sourabhjains** [comment]
Fixed: https://github.com/linux-ras/ServiceReport/commit/a1d474d81a516407d4354218abd4f9b24f463711
