### ISSUE TITLE
FAdump: format of sysfs interface that exposes the memory reservation has changed upstream

### ISSUE THREAD

**Issue by mwbringmann** [linux-ras/ServiceReport#2]
Installed a kernel build (5.3.13-1-default) and configured it for FAdump,
then ran servicereport as follows:

 ./servicereport -v -r
servicereport 2.2.1
Daemon availability checks                          PASS
  rtas_errd                                         PASS
  irqbalance                                        PASS
FADump configuration check                          FAIL
  Dump component in initial ramdisk                 PASS
  FADump enabled check                              PASS
  FADump registration check                         PASS
  Service status                                    PASS
  kdump package                                     PASS
  Fadump attributes in /etc/sysconfig/kdump         PASS
  kexec package                                     PASS
  Memory reservation                                UNKNOWN  Unable to Fix

Talked to Sourabh, and he mentioned that it is happening because the format of sysfs interface that exposes the FADump memory reservation has changed.  We are using an upstream kernel, where the patch that changes the interface are not picked by any distro yet.

**Comment by sourabhjains** [comment]
Thanks @mwbringmann for reporting the issue.

**Comment by sourabhjains** [comment]
Fixed: https://github.com/linux-ras/ServiceReport/commit/076b3db3bb244fe5525885d52aa5a4b494561743
