### ISSUE TITLE
servicereport is not activating rtas_errd when it is in inactive state

### ISSUE THREAD

**Issue by shirishaganta1** [linux-ras/ServiceReport#20]
Steps to Recreate:
1. check for rtas_errd service status
systemctl status rtas_errd
2. stop the rtas_errd service
systemctl stop rtas_errd
3. Run servicereport with recovery option
servicereport -p daemon -r
4. check for rtas_errd service status whether service has started or not
systemctl status rtas_errd

--log--

localhost:~ # systemctl is-active rtas_errd
inactive
localhost:~ # servicereport -p daemon -r -f rtas_errd.log
servicereport 2.2.2

Daemon availability checks                          PASS

  rtas_errd                                         PASS
  irqbalance                                        PASS
localhost:~ # cat rtas_errd.log
Apr 22 12:15:11 servicereport.daemon[11348]: INFO - rtas_errd is enabled
Apr 22 12:15:11 servicereport.daemon[11348]: INFO - irqbalance is enabled
localhost:~ # systemctl is-active rtas_errd
inactive
localhost:~ #

**Comment by sourabhjains** [comment]
Thanks @shirishaganta1 for reporting the issue.

Currently, ServiceReport only rely on enabled/disabled status of daemon which may not
good enough to ensure deamon runs all all the time.

A fix has been proposed and sent for review.

Thanks,
Sourabh Jain

**Comment by sourabhjains** [comment]
Fixed https://github.com/linux-ras/ServiceReport/commit/9a44352ff9a8b83e57fcb9a647c9ae8c13efb4f5
