### ISSUE TITLE
crashkernel configured by servicereport is not sufficient on max config machines during fadump

### ISSUE THREAD

**Issue by Pavithra1602** [linux-ras/ServiceReport#21]
Bug 193671 - RHEL8.5 [ 4.18.0-321.el8.ppc64le ] [ fleetwood / P9 ] [ 32TB/192c ]: crashkernel configured by servicereport is not sufficient on max config machines during fadump

Crash kernel value for fadump is not updated based on below table.

System Memory          crashkernel setting (crashkernel=)
-----------------------------------------------------------------

4 GB     - 32 GB    1024 MB
32 GB    - 64 GB     1024 MB
64 GB    - 128 GB    2048 MB
128 GB   - 1024 GB    4 GB
1024 GB  - 2048 GB    6 GB
2048 GB  - 4096 GB    12 GB
4096 GB  - 8192 GB    20 GB
8 TB     - 16 TB    36 GB
16 TB    -  32 TB    64 GB                    
32 TB    -  64 TB    80 GB        
64 TB    -  >            180 GB

[console_log_fadump.txt](https://github.com/linux-ras/ServiceReport/files/6838660/console_log_fadump.txt)
[console_log.txt](https://github.com/linux-ras/ServiceReport/files/6838663/console_log.txt)

**Comment by sourabhjains** [comment]
Hello @Pavithra1602 

Fix for above issue available upstream.
https://github.com/linux-ras/ServiceReport/commit/55a13db1c256f0ed8c53292e48a4592491ba79bd

Thanks

**Comment by sourabhjains** [comment]
Hello @Pavithra1602 

Shell we close this issue?

Thanks
