### ISSUE TITLE
servicereport complains that initrd does not have kdump component when fadump is configured.

### ISSUE THREAD

**Issue by Pavithra1602** [linux-ras/ServiceReport#23]
Logs:
=====

Daemon availability checks                          PASS
  rtas_errd                                         PASS
  irqbalance                                        PASS
FADump configuration check                          FAIL
  Active dump                                       PASS
  Dump component in initial ramdisk                 FAIL     Unable to Fix
  FADump enabled check                              PASS
  FADump registration check                         PASS
  Service status                                    PASS
  kexec package                                     PASS
  Memory reservation                                FAIL     Auto Fixed, Needs Reboot
Package availability check                          PASS
  ppc64-diag                                        PASS
  irqbalance                                        PASS
  perf                                              PASS     Auto Fixed
  sos                                               PASS
  powerpc-utils                                     PASS

**Comment by hbathini** [comment]
This is due to fadump initrd isolaton feature.
Observed on RHEL-9.0 (having https://bugzilla.linux.ibm.com/show_bug.cgi?id=191132) and
RHEL-8.6 (having https://bugzilla.linux.ibm.com/show_bug.cgi?id=191125).

The fix would be to look for either of kdumpbase or zz-fadumpinit dracut module in initrd for fadump case..

**Comment by sourabhjains** [comment]
Hello @Pavithra1602 

The fix for this issue is upstream now.

Thanks for the support.

https://github.com/linux-ras/ServiceReport/commit/20c21fb4a4bbebe4f48e0cdff1ff4e184b7edbd1

- Sourabh Jain
