### ISSUE TITLE
Add option to test kdump/fadump?

### ISSUE THREAD

**Issue by mwbringmann** [linux-ras/ServiceReport#3]
Would it be useful to add an option to the tool to test the dump configuration?

**Comment by sourabhjains** [comment]
Hello @mwbringmann 

With the above description, I am not able to understand what you want exactly.
Could you please provide more details on the new feature.

-Sourabh Jain

**Comment by sourabhjains** [comment]
Hello @mwbringmann 

We do have -d option that triggers the kernel crash if Kdump/Fadump is configured properly.

Did you try that option?

Thanks,
Sourabh Jain

**Comment by sourabhjains** [comment]
No updated on this issue, so closing it.
