### ISSUE TITLE
fadump configuration check is failing if there is active dump running on the machine.

### ISSUE THREAD

**Issue by seeteena** [linux-ras/ServiceReport#8]
# servicereport -r
servicereport 2.2.2

sh: line 0: echo: write error: Operation not permitted
Daemon availability checks                          PASS

  rtas_errd                                         PASS
  irqbalance                                        PASS

FADump configuration check                          FAIL

  Dump component in initial ramdisk                 PASS
  FADump enabled check                              PASS
  FADump registration check                         FAIL     Unable to Fix
  Service status                                    FAIL     Unable to Fix
  kdump package                                     PASS
  Fadump attributes in /etc/sysconfig/kdump         PASS
  kexec package                                     PASS
  Memory reservation                                PASS

HTX configuration check                             FAIL

  HTX Installation path                             PASS
  HTX service status                                FAIL

Package availability check                          PASS

  ppc64-diag                                        PASS
  irqbalance                                        PASS
  perf                                              PASS
  supportutils                                      PASS
  powerpc-utils                                     PASS

**Comment by seeteena** [comment]
Sourabh is aware of this issue. please see 186058 for more details.

**Comment by sourabhjains** [comment]
Thanks @seeteena for reporting the issue.

We will add a check in FADump/kdump plugin to cover this scenario.

**Comment by sourabhjains** [comment]
Added new check in Kdump and FADump plugin to handle this scenario.

Fixed: https://github.com/linux-ras/ServiceReport/commit/c9feebe21448e1e2691c4195c15009ef85e9d4e8

Thanks,
Sourabh Jain
